[env:adafruit_metro_m0]
platform = atmelsam
board = adafruit_metro_m0
framework = arduino

lib_deps =
    robtillaart/Statistic @ ^1.0.4
    robtillaart/Gauss
    arduino-libraries/WiFi101
    arduino-libraries/ArduinoMqttClient

upload_delay = 2000