M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-06-04T12:29:19+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-04T12:29:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X92.0Y-60.1
X92.1Y-129.2
X208.9Y-60.2
X208.9Y-129.1
M30
